### ISSUE TITLE
SSO profile failing

### ISSUE THREAD

**Issue by jasondearingcnx** [sethkor/connect-backup#27]
Hello. Thanks for making such a useful tool. Does connect-backup currently support SSO for aws profiles? I'm getting an error, but only when I try to use a profile I've signed in as using "aws configure sso":

2021/05/25 14:52:22 NoCredentialProviders: no valid providers in chain
caused by: EnvAccessKeyNotFound: failed to find credentials in the environment.
SharedCredsLoad: failed to load profile, _MySSOProfileName_.
EC2RoleRequestError: no EC2 instance role found
caused by: RequestError: send request failed

**Comment by sethkor** [comment]
I'm not sure why this wouldn't work looking at the examples AWS provide, although I don't use AWS SSO myself.  Can you provide me an output of the actual aws sso command please @jasondearingcnx ?

**Comment by jasondearingcnx** [comment]
Sorry, just a profiles issue locally.
