### ISSUE TITLE
Unpublished contact flows interrupt the rest of the backup

### ISSUE THREAD

**Issue by hatchcanon** [sethkor/connect-backup#28]
Hi, thanks for making this tool.

I've encountered an issue when there is an unpublished contact flow. In the logs you get
`2021/10/01 18:57:38 Failed to describe flow`

when I ran to describe the contact flow manually, I found the reason was 
`An error occurred (ContactFlowNotPublishedException) when calling the DescribeContactFlow operation: Contact flow not published`

Now when it hits this roadblock it doesn't backup the rest of the contact flows and continues to backing up users. Is it possible to skip all the unpublished contactflows and backup the other contact flows?

**Comment by sethkor** [comment]
Should be a quick fix.  I'll output any errors describing the flow and rather than exit, just continue with the loop

**Comment by sethkor** [comment]
Fixed in v0.0.24

**Comment by hatchcanon** [comment]
Thanks! Do you mind fixing the lambda too? I should've specified that was what I was using.

**Comment by sethkor** [comment]
@hatchcanon it's the exact same code.  Did you make the lambda and redeploy it?

**Comment by hatchcanon** [comment]
I apologize, I just tested again and turns out I was using the old zip. Thank you again
